package model.Dao;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import application.util.customMessage.DisplayMessage;
import model.Dao.db.DatabaseQuery;

class TakeUserSaltDAO {

	static int takeUserSalt(Connection con_read, int id_user) {

		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			try(PreparedStatement ps_salt = con_read.prepareStatement(DatabaseQuery.takeUserSalt()){
				ps_salt.setInt(1, id_user);
				try(ResultSet rsSalt = ps_salt.executeQuery()){

					if (rsSalt.next()) {

						Blob userSaltBlob = rsSalt.getBlob("salt_value");
						System.out.println("\nSalt = " + rsSalt.getBlob("salt_value").toString());
						return rsId.getInt("id"); 
					}
					
					
						
							
						}else {
							DisplayMessage.showPanel("Errore nell'individuazione dell'ID nel DB. Riprova");
							return 0;
						}
					}
				}
			}catch(ClassNotFoundException|SQLException e) {
				DisplayMessage.showPanel("Si è verificato un problema di connessione!");
				e.printStackTrace();
			}

			return 0;
		}

	}
